![](https://s2.ax1x.com/2019/11/16/MwDPdH.png)

## 数据规范化示例

### Min-Max 规范化

In [4]:
from sklearn import preprocessing
import numpy as np

x = np.array([[0, -3, 1],
              [3, 1, 2],
              [0, 1, -1]])

min_max_scaler = preprocessing.MinMaxScaler()
minmax_x = min_max_scaler.fit_transform(x)
print(minmax_x)

# 默认 axis=0 

[[0.         0.         0.66666667]
 [1.         1.         1.        ]
 [0.         1.         0.        ]]


### Z-Score 规范化

In [5]:
scaled_x = preprocessing.scale(x,axis=1)

print(scaled_x)

# 默认 axis=0 

[[ 0.39223227 -1.37281295  0.98058068]
 [ 1.22474487 -1.22474487  0.        ]
 [ 0.          1.22474487 -1.22474487]]


### 小数定标规范化

In [6]:
j = np.ceil(np.log10(np.max(abs(x))))
scaled_x_02 = x/(10**j)
print(scaled_x_02)

[[ 0.  -0.3  0.1]
 [ 0.3  0.1  0.2]
 [ 0.   0.1 -0.1]]


## 总结

还好之前自己简略翻看过 scikit-learn 的教学，有必要重新看一遍再理解一番。