<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#CNN-网络" data-toc-modified-id="CNN-网络-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>CNN 网络</a></span></li></ul></div>

1. 进一步了解 CNN 网络，尤其是卷积的原理；
1. 初步了解 LeNet 和 AlexNet；
1. 选择学习深度学习框架；
1. 使用 Keras 深度学习框架完成第一个深度学习任务。

## CNN 网络

卷积：<img src="https://static001.geekbang.org/resource/image/9d/cf/9d1bb65b30517775b632c10c1cb1c0cf.jpg" style="width:500px">

1. 卷积核翻转 180 度，得到：<img src="https://static001.geekbang.org/resource/image/cb/33/cb755c0cf5868c39d71e0392146c4833.jpg" style="width:200px"><br><br>
1. 将卷积核的第一个元素对准矩阵 X 左上角的第一个元素，对应元素相乘，然后再相加，得到：10*1+10*1+10*0+10*1+5*0+5*-1+10*0+5*-1+5*-1=15<br><br><img src="https://static001.geekbang.org/resource/image/90/11/90a3bbabba732a2a7ad97a24f3587411.jpg" style="width:300px"><br><br>
1. 重复第二步，得到最终结果：<img src="https://static001.geekbang.org/resource/image/b8/6c/b824778383e3a898fe2399fb2eb8846c.jpg" style="width:200px">

代码演示如下：

In [1]:
import numpy as np
import pylab  # numpy 交互式运行
from scipy import signal
# 设置原图像
img = np.array([[10, 10, 10, 10, 10], 
                [10, 5, 5, 5, 10], 
                [10, 5, 5, 5, 10], 
                [10, 5, 5, 5, 10], 
                [10, 10, 10, 10, 10]])
# 定义卷积核
fil = np.array([[ -1,-1, 0], 
                [ -1, 0, 1], 
                [ 0, 1, 1]])
# 对原图像进行卷积操作
res = signal.convolve2d(img, fil, mode='valid')
# 输出卷积结果
print(res)

[[ 15  10   0]
 [ 10   0 -10]
 [  0 -10 -15]]


***

对图像进行卷积操作的原因：

In [3]:

import matplotlib.pyplot as plt
import pylab
import cv2
import numpy as np
from scipy import signal
# 读取灰度图像
img = cv2.imread("./image/image_learn/haibao.jpg", 0)
# 显示灰度图像
plt.imshow(img,cmap="gray")
pylab.show()
# 设置卷积核
fil = np.array([[ -1,-1, 0],
                [ -1, 0, 1],
                [  0, 1, 1]])
# 卷积操作
res = signal.convolve2d(img, fil, mode='valid')
print(res)
#显示卷积后的图片
plt.imshow(res,cmap="gray")
pylab.show()

ModuleNotFoundError: No module named 'cv2'